Px score for bugs
openshift/network-tools pull request #128
Opened 2024-05-22 22:11 UTC by CFields651

This PR adds the "PX Impact Score" to the output for --new-bugs to the ./network_bugs_overview script. PX Impact Score is from the "Product Experience" tab in OCPBUGS and is a numeric "severity" that is calculated by an algorithm described here: [PX Prioritization Algorithm Details](https://spaces.redhat.com/pages/viewpage.action?spaceKey=PPE&title=PX+Prioritization+Algorithm+Details)

Basically, every bugs starts out with a score of 6000. There are 4 factors that can increase the score up to 12000:

- The total quantity of linked cases
- The quantity of linked cases with a specific severity
- The "complexity" and quantity of the linked cases
- PX properties like "Impact range" and "technical impact" set manually by me (or anyone)

I'd like to get Px Impact Score into the output for new bugs as an acid test for prioritization.  Higher score means more customer impact.

2024-05-23 18:03 UTC, CFields651 commented
/retest

2024-05-27 13:58 UTC, npinaeva commented
cc @ricky-rav

2024-05-27 14:58 UTC, ricky-rav requested changes
I tried it out with the changes I suggested and it works! Also on a bug where I temporarily added a px score. Two suggested changes. Thanks, Chris!

2024-05-27 14:58 UTC, ricky-rav commented on jira-scripts/network_bugs_overview
> +        if str(bug_issuetype) == "Bug" and str(bug) in "OCPBUGS":
Here I think you meant `"OCPBUGS" in str(bug)`

2024-05-27 14:58 UTC, ricky-rav commented on jira-scripts/network_bugs_overview
> +            print(f"- [{bug}]({bug_url}) - [{bug_px_score}] {bug_summary}")
So this will print `[None]` when no px score is on the jira ticket. How about we replace `None` with something more explicit?
```
            if bug_px_score is not None:                                                                                                                                                      
                bug_px_score=int(bug_px_score)                                                                                                                                                
            else:                                                                                                                                                                             
                bug_px_score = "no px score"    
```

2024-05-30 07:55 UTC, ricky-rav commented
/lgtm 
Thanks, Chris!

2024-06-06 07:36 UTC, npinaeva commented
/lgtm

2024-06-06 07:37 UTC, npinaeva commented
/retitle NO-JIRA: Px score for bugs

2024-06-06 07:42 UTC, merged