SDN-1492: Base network-tools on top of openshift-tools
openshift/network-tools pull request #24
Opened 2021-01-13 10:33 UTC by tssurya

This patch also moves the installation of ovnkube-trace to the Dockerfile so that it is available in the image directly instead of having to install it in each script.

Users can invoke ovnkube-trace using:

```
oc adm network-tools -- ovnkube-trace --tcp --src <src-pod-name> --dst <dst-pod-name> --loglevel=5
```
once we integrate this image with oc client (this is WIP right now).

Note: I haven't changed the centos DockerFile to be based on openshift-tools. I think we can keep that image as testing image and have some level of freedom there.

/assign @rcarrillocruz

2021-01-13 11:09 UTC, tssurya commented
/test images

2021-01-13 11:10 UTC, tssurya commented
/hold CI is not picking up latest changes and something is funky with the /test command. Checking.

2021-01-13 11:12 UTC, tssurya commented
/retest

2021-01-14 18:08 UTC, tssurya commented
/hold cancel.

This is good to go.

2021-01-14 18:09 UTC, tssurya commented
/hold cancel

2021-01-16 14:34 UTC, tssurya commented
/test e2e-aws

2021-01-18 11:56 UTC, danielmellado commented on Dockerfile.rhel7
>  FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.7 AS builder
The Dockerfile says rhel7 but the registry says rhel8. I assume this would be the correct one but if so you'd need to rename the file for clarification.

2021-01-18 11:56 UTC, danielmellado requested changes
Looks like I found a typo ;)

2021-01-18 12:09 UTC, tssurya commented on Dockerfile.rhel7
>  FROM registry.svc.ci.openshift.org/ocp/builder:rhel-8-golang-1.15-openshift-4.7 AS builder
heh, I was secretly hoping no one would ask me to change the file name because I have to open PRs against `release` and `art` repos. However I guess someone would have to do this at some point. Guess I might as well change it.

However I need to get this change for the `Dockerfile` specially in before I can open those PRs. So let's get this in and then I change the art and release repos and come back to changing this filename.

2021-01-18 12:12 UTC, danielmellado commented
As per the workflow on CI/Art and so, let's get this merged, but please don't forget to create a follow-up patch correcting the misleading rhel dockerfile name situation!

2021-01-18 12:12 UTC, danielmellado commented
/approve

2021-01-18 12:28 UTC, juanluisvaladas commented
/lgtm

2021-01-18 13:11 UTC, tssurya commented
> As per the workflow on CI/Art and so, let's get this merged, but please don't forget to create a follow-up patch correcting the misleading rhel dockerfile name situation!

Actually I think we are good even if we don't rename: Looking at the instruction template for ocp-build-data repo: https://github.com/openshift/ocp-build-data/blob/181a2099fc26226e7349af2bebabae0dfd25441e/example/images/template.yml#L84 , even the dockerfile name should be a non-default one, whatever that means, but seems to have the rhel7 tag.

Anyways I'll keep an eye out if things don't change automatically to the `.rhel8` extension.

2021-01-18 14:38 UTC, tssurya commented
/test e2e-aws

2021-01-18 17:08 UTC, merged