SDN-1521: oc-plumbing-related-refactoring-ovn-scripts
openshift/network-tools pull request #26
Opened 2021-01-15 22:54 UTC by tssurya

Though the change looks big, its not:

- I've refactored the folder structure under debug-scripts since in the image all scripts get copied into /usr/bin without retaining their folder structure.
- I've removed the `version` and `debug` files since they don't seem really necessary.
- I've moved some common functions into `common`.

TODO: Still need to refactor the scripts for SDN and move more stuff into common.

From now on any new script added to ovn should start with `ovn_*` and similarly for sdn. Then they should get called from the main script `network-tools`.

/cc @rcarrillocruz 
@astoycos : I've also modified your script moving the pod creation portions to a more common place. You can also push a PR later on to change the rest of the script accordingly and remove the comment of the script from the `network-tools` call.

2021-01-15 22:54 UTC, tssurya commented
/hold

until https://github.com/openshift/network-tools/pull/24 merges.

2021-01-28 20:43 UTC, tssurya commented
/hold cancel

2021-01-29 11:34 UTC, tssurya commented
/assign @juanluisvaladas @rcarrillocruz @astoycos

2021-01-29 12:36 UTC, juanluisvaladas requested changes
Seems pretty good, I just have a couple nitpicks.

2021-01-29 12:36 UTC, juanluisvaladas commented on debug-scripts/common
> +}
Per POSIX standard, every line must finish with a new line character in the end.

2021-01-29 12:36 UTC, juanluisvaladas commented on debug-scripts/sdn_pod_to_svc_connectivity
> +main
Also missing the new line character in the end.

2021-01-29 12:36 UTC, juanluisvaladas commented on debug-scripts/sdn_node_connectivity
> +    help
Do we always want to display help?

2021-01-29 12:36 UTC, juanluisvaladas commented on debug-scripts/sdn_pod_to_pod_connectivity
> +    help
Same.

2021-01-29 12:36 UTC, juanluisvaladas commented on debug-scripts/sdn_pod_to_svc_connectivity
> +    help
same

2021-01-29 12:36 UTC, juanluisvaladas commented on debug-scripts/ovn_pod_to_pod_connectivity
> +    help
same

2021-01-29 12:36 UTC, juanluisvaladas commented on debug-scripts/ovn_pod_to_svc_connectivity
> +    help
same

2021-01-29 12:36 UTC, juanluisvaladas commented on debug-scripts/network-tools
> +fi
again the newline

2021-01-29 13:10 UTC, tssurya commented on debug-scripts/sdn_node_connectivity
> +    help
yea agreed not needed.

2021-01-29 13:14 UTC, tssurya commented
> Seems pretty good, I just have a couple nitpicks.

thanks Juan for the review. Have addressed the nits.

2021-01-29 13:53 UTC, juanluisvaladas commented
/approve
/lgtm

2021-01-29 14:58 UTC, merged