Adding ovn_cleanConntrack for BZ2043094
openshift/network-tools pull request #55
Opened 2022-02-15 11:42 UTC by ptrnull

Script to detect persistent conntrack lines that should have been removed (BZ [2043094])
For testing purposes a fake conntrack line based in our cluster networks can be inserted:
```
# oc rsh -n openshift-ovn-kubernetes ovnkube-node-XXXXX
sh-4.4# conntrack -I -p udp -s 10.130.1.44 -d 172.30.2.3 --sport 3333 --dport 60003 -t 60                                                                    
conntrack v1.4.4 (conntrack-tools): 1 flow entries have been created.
sh-4.4# exit
exit
# ./ovn_cleanConntrack
#Generating lines for node (rna1-master-2.rna1.cloud.lab.eng.bos.redhat.com) subnet:10.128.2.0                                                               
#Raw line:udp 17 52 src=10.130.1.44 dst=172.30.2.3 sport=3333 dport=60003 src=172.30.2.3 dst=10.130.1.44 sport=60003 dport=3333 mark=0 secctx=system_u:object_r:unlabeled_t:s0 use=1
conntrack -D -s 10.130.1.44 -d 172.30.2.3 -r 172.30.2.3 -q 10.130.1.44
conntrack -D -s 10.130.1.44 -d 172.30.2.3
conntrack -D -s 10.128.2.0 -d 172.30.2.3 -r 172.30.2.3 -q 10.128.2.0

```
A log file is generated with some info in ovn_cleanConntrack.${timestamp}.log

2022-02-15 19:21 UTC, dougsland commented
@ptrnull is there a bug report around this PR?

2022-02-15 23:34 UTC, ptrnull commented
> @ptrnull is there a bug report around this PR?

Yes @dougsland, is in the subject and the content of the PR: [BZ2043094](https://bugzilla.redhat.com/show_bug.cgi?id=2043094)

2022-02-16 00:12 UTC, dougsland commented
> > @ptrnull is there a bug report around this PR?
> 
> Yes @dougsland, is in the subject and the content of the PR: [BZ2043094](https://bugzilla.redhat.com/show_bug.cgi?id=2043094)

Thanks for adding context.

2022-02-16 01:34 UTC, dougsland commented
I would suggest address the warnings from shellcheck 

```
network-tools$ shellcheck debug-scripts/ovn_cleanConntrack 

In debug-scripts/ovn_cleanConntrack line 21:
			words=$(echo $line| wc -w)
                                     ^---^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			words=$(echo "$line"| wc -w)


In debug-scripts/ovn_cleanConntrack line 22:
			protos=$(echo $line | cut -d';' -f1)
                                      ^---^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			protos=$(echo "$line" | cut -d';' -f1)


In debug-scripts/ovn_cleanConntrack line 23:
			ip=$(echo $line | cut -d';' -f2)
                                  ^---^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			ip=$(echo "$line" | cut -d';' -f2)


In debug-scripts/ovn_cleanConntrack line 24:
			port1=$(echo $line | cut -d';' -f3)
                                     ^---^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			port1=$(echo "$line" | cut -d';' -f3)


In debug-scripts/ovn_cleanConntrack line 25:
			if [ ${words} -gt 1 ]; then
                             ^------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			if [ "${words}" -gt 1 ]; then


In debug-scripts/ovn_cleanConntrack line 27:
				while [ ${count} -le ${words} ]; do
                                                     ^------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
				while [ ${count} -le "${words}" ]; do


In debug-scripts/ovn_cleanConntrack line 29:
					ports=$(echo ${line} | cut -d';' -f${count})
                                                     ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
					ports=$(echo "${line}" | cut -d';' -f${count})


In debug-scripts/ovn_cleanConntrack line 30:
					cports=$(echo ${ports}| wc -w)
                                                      ^------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
					cports=$(echo "${ports}"| wc -w)


In debug-scripts/ovn_cleanConntrack line 31:
					while [ ${cports} -gt 0 ]; do
                                                ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
					while [ "${cports}" -gt 0 ]; do


In debug-scripts/ovn_cleanConntrack line 32:
						port=$(echo ${ports}| cut -d' ' -f${cports})
                                                            ^------^ SC2086: Double quote to prevent globbing and word splitting.
                                                                                  ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
						port=$(echo "${ports}"| cut -d' ' -f"${cports}")


In debug-scripts/ovn_cleanConntrack line 33:
						proto=$(echo ${protos}| cut -d' ' -f${cports})
                                                             ^-------^ SC2086: Double quote to prevent globbing and word splitting.
                                                                                    ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
						proto=$(echo "${protos}"| cut -d' ' -f"${cports}")


In debug-scripts/ovn_cleanConntrack line 47:
		echo -e "Final services" >> ${LOG}
                ^-- SC2129: Consider using { cmd1; cmd2; } >> file instead of individual redirects.
                                            ^----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
		echo -e "Final services" >> "${LOG}"


In debug-scripts/ovn_cleanConntrack line 48:
		echo "----------------" >> ${LOG}
                                           ^----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
		echo "----------------" >> "${LOG}"


In debug-scripts/ovn_cleanConntrack line 49:
		echo -e ${services} >> ${LOG}
                        ^---------^ SC2086: Double quote to prevent globbing and word splitting.
                                       ^----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
		echo -e "${services}" >> "${LOG}"


In debug-scripts/ovn_cleanConntrack line 61:
			ips=$(echo ${line} | cut -d';' -f1)
                                   ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			ips=$(echo "${line}" | cut -d';' -f1)


In debug-scripts/ovn_cleanConntrack line 62:
			cips=$(echo ${ips}|wc -w)
                                    ^----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			cips=$(echo "${ips}"|wc -w)


In debug-scripts/ovn_cleanConntrack line 63:
			nodes=$(echo ${line} | cut -d';' -f2)
                                     ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			nodes=$(echo "${line}" | cut -d';' -f2)


In debug-scripts/ovn_cleanConntrack line 64:
			cnodes=$(echo ${nodes} | wc -w)
                        ^----^ SC2034: cnodes appears unused. Verify use (or export if used externally).
                                      ^------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			cnodes=$(echo "${nodes}" | wc -w)


In debug-scripts/ovn_cleanConntrack line 65:
			ports=$(echo ${line} | cut -d';' -f3)
                                     ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			ports=$(echo "${line}" | cut -d';' -f3)


In debug-scripts/ovn_cleanConntrack line 66:
			cports=$(echo ${ports} | wc -w)
                                      ^------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			cports=$(echo "${ports}" | wc -w)


In debug-scripts/ovn_cleanConntrack line 67:
			protocols=$(echo ${line} | cut -d';' -f4)
                                         ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			protocols=$(echo "${line}" | cut -d';' -f4)


In debug-scripts/ovn_cleanConntrack line 69:
			if [ ${cips} -gt 1 ]; then			
                             ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
			if [ "${cips}" -gt 1 ]; then			


In debug-scripts/ovn_cleanConntrack line 71:
				if [ ${cports} -gt 1 ]; then
                                     ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
				if [ "${cports}" -gt 1 ]; then


In debug-scripts/ovn_cleanConntrack line 73:
					while [ ${count} -le ${cips} ]; do
                                                             ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
					while [ ${count} -le "${cips}" ]; do


In debug-scripts/ovn_cleanConntrack line 74:
						ip=$(echo ${ips} | cut -d' ' -f${count})
                                                          ^----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
						ip=$(echo "${ips}" | cut -d' ' -f${count})


In debug-scripts/ovn_cleanConntrack line 76:
						node=$(echo ${nodes} | cut -d' ' -f${count})
                                                            ^------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
						node=$(echo "${nodes}" | cut -d' ' -f${count})


In debug-scripts/ovn_cleanConntrack line 77:
						while [ ${countports} -le ${cports} ]; do
                                                                          ^-------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
						while [ ${countports} -le "${cports}" ]; do


In debug-scripts/ovn_cleanConntrack line 78:
							port=$(echo ${ports} | cut -d' ' -f${countports})
                                                                    ^------^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
							port=$(echo "${ports}" | cut -d' ' -f${count [...]

2022-02-16 01:43 UTC, flavio-fernandes commented on debug-scripts/ovn_cleanConntrack
> +			words=$(echo $line| wc -w)
NIT: add a space before '|'

2022-02-16 01:43 UTC, flavio-fernandes commented on debug-scripts/ovn_cleanConntrack
> +					cports=$(echo ${ports}| wc -w)
NIT: add space before '|'

2022-02-16 01:43 UTC, flavio-fernandes commented on debug-scripts/ovn_cleanConntrack
> +						port=$(echo ${ports}| cut -d' ' -f${cports})
NIT: add space before '|'

2022-02-16 01:43 UTC, flavio-fernandes commented on debug-scripts/ovn_cleanConntrack
> +			cips=$(echo ${ips}|wc -w)
NIT: add space before '|'

2022-02-16 01:43 UTC, flavio-fernandes commented on debug-scripts/ovn_cleanConntrack
> +	dst1O2=$(echo ${dst1}|cut -d';' -f1 | cut -d'.' -f2)
NIT: add space before '|'

2022-02-16 12:07 UTC, ptrnull commented
@dougsland @flavio-fernandes thanks for the review! fixes implemented.

2022-02-17 01:24 UTC, dougsland commented
great. cool tool to have also around upstream. Maybe, in a future create a patch to make it work in raw k8s env as well.

2022-02-17 16:58 UTC, ptrnull commented
> great. cool tool to have also around upstream. Maybe, in a future create a patch to make it work in raw k8s env as well.

Sure!, can we have it reviewed and merged?

2022-02-17 17:00 UTC, abhat commented
@ptrnull thank you for adding this script. Really appreciate your contribution. I think we need to make the bugzilla bot happy. please work with @tssurya on that.

2022-02-17 17:06 UTC, ptrnull commented
@abhat It complains because the BZ is already closed, can we assigned it to a different BZ?

2022-02-17 17:22 UTC, tssurya commented
/bugzilla refresh

2022-02-17 17:23 UTC, tssurya commented
/bugzilla refresh

2022-02-17 17:25 UTC, tssurya commented
/bugzilla refresh

2022-02-17 17:58 UTC, tssurya approved these changes
/lgtm
thanks @ptrnull for the script and your patience in writing this in bash :dagger: 
there are few user facing TODO's we can figure out late.
Approving this for now, and perhaps when CU runs this they might have more feedback/iterations we need to do.

2022-02-17 17:58 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +getConntrack
TODO: In future add a "-h" helper option to the script so that user knows how to use this. + be prepared that there is a file that the info gets logged into.

2022-02-17 17:58 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +getConntrack
TODO: add a "-v"  verbose option while running the script. When I tried to run this, it simply didn't return anything which is fine. But at least while waiting I'd have loved to see:
Collecting service info..
Collecting endpoints info...
Constructing cache for clusterIP services..
Logged things into the file blah..

kind of thing.

2022-02-17 17:58 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +		for conntrack in $(echo "${conntracks}" | sed 's/udp/\nudp/g' | sed 's/\[UNREPLIED\]//g' | sed 's/\[ASSURED\]//g' | tr -s ' '); do
so logic is:

1. construct service cache for clusterIPs and UDP alone
2. get conntrack entries, ONLY UDP ones
3. eliminate things not in serviceCIDR
4. finally check if dstIP in first tuple of conntrack entry != clusterIP and srcIP of second tuple in conntrack entry != endpointsIP, then add that entry to the deletion list.

2022-02-17 18:05 UTC, tssurya commented
not sure why the bot auto approved this?! I wanted finally approve from @dcbw

2022-02-17 18:08 UTC, tssurya commented
/approve cancel

2022-02-17 19:00 UTC, dcbw commented on debug-scripts/ovn_cleanConntrack
> +	dst1O2=$(echo "${dst1}" | cut -d';' -f1 | cut -d'.' -f2)
@ptrnull I feel like there has to be a better way to do this check than just assuming that the Service CIDR is an IPv4 /16

2022-02-17 19:03 UTC, dcbw commented on debug-scripts/ovn_cleanConntrack
> +network=$(oc get network cluster -o jsonpath='{ .spec.serviceNetwork[] }')
@ptrnull could we make this "svcnetwork" ?

2022-02-17 19:03 UTC, dcbw commented on debug-scripts/ovn_cleanConntrack
> +function isContrackinNetwork(){
@ptrnull could we make this isContrackinSvcNetwork?

2022-02-17 19:18 UTC, trozet requested changes

2022-02-17 19:18 UTC, trozet commented on debug-scripts/ovn_cleanConntrack
> +	nodesubnet=$(oc get node "${node}" -o jsonpath='{.metadata.annotations.k8s\.ovn\.org/node-subnets}'  | jq .default | xargs | cut -d'/' -f1)
this shouldn't be the node subnet, it should be the mp0 ip according to the bz, which would be the 2nd IP address in this node subnet

2022-02-17 19:23 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +	dst1O2=$(echo "${dst1}" | cut -d';' -f1 | cut -d'.' -f2)
yes, there is and I can implement the func to calculate it but somebody was requesting the delivery of the script asap...

2022-02-17 19:23 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +network=$(oc get network cluster -o jsonpath='{ .spec.serviceNetwork[] }')
sure, changed it, thanks!

2022-02-17 19:23 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +function isContrackinNetwork(){
changed it too, thanks!

2022-02-22 10:50 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +	nodesubnet=$(oc get node "${node}" -o jsonpath='{.metadata.annotations.k8s\.ovn\.org/node-subnets}'  | jq .default | xargs | cut -d'/' -f1)
changed it to the .2

2022-02-22 13:03 UTC, squeed commented on debug-scripts/ovn_cleanConntrack
> +clusternetwork=$(oc get network cluster -o jsonpath='{ .spec.clusterNetwork[].cidr }' | cut -d'/' -f1 | sed -e 's/.$/2/')
Can this handle dual-stack clusters?

2022-02-22 13:34 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +clusternetwork=$(oc get network cluster -o jsonpath='{ .spec.clusterNetwork[].cidr }' | cut -d'/' -f1 | sed -e 's/.$/2/')
Hello @squeed No, the use case is for single stack IPv4 cluster.

2022-02-28 18:10 UTC, trozet commented on debug-scripts/ovn_cleanConntrack
> +	nodesubnet=$(echo "${nodesubnet}" | sed -e 's/.$/2/')
it's possible for nodes not to have a /24. In that case this logic may not work. Do we care? Or for this use case is using /24 fine?

2022-03-01 08:14 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +	nodesubnet=$(echo "${nodesubnet}" | sed -e 's/.$/2/')
For this use case using /24 should be fine but to improve it I can use a parameter and include a comment in the header of the script to let the final user configure it in the case it's different from /24.

2022-03-01 10:39 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +clusternetwork=$(oc get network cluster -o jsonpath='{ .spec.clusterNetwork[].cidr }' | cut -d'/' -f1 | sed -e 's/.$/2/')
while the use case rn is for IPV4, we should fix this if possible.

2022-03-01 10:48 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +	nodesubnet=$(echo "${nodesubnet}" | sed -e 's/.$/2/')
@ptrnull : we are sure all the user's clusters use /24 ? I feel like we should outline these things somewhere, 
Assumptions:
1) this script only supports UDP stale entries
2) this script only considers clusterIP services
3) this script only works on IPV4 single stack env
4) this script assumes nodesubnet is the default /24 cidr

etc..

2022-03-01 10:54 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +	nodesubnet=$(echo "${nodesubnet}" | sed -e 's/.$/2/')
I'd have preferred we took the IP from ovn-k8s-mp0 interface, but we can do that in a cleanup if needed.

2022-03-01 12:02 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +	dst1O2=$(echo "${dst1}" | cut -d';' -f1 | cut -d'.' -f2)
I've added the cases for /8 and /24, plus the original one /16, is that enough?

2022-03-01 12:05 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +	nodesubnet=$(echo "${nodesubnet}" | sed -e 's/.$/2/')
Added the -h flag, it prints:
```
This script does not actually clean up anything
It simply gives the potential list of things that might have to be cleaned up.
It only supports UDP stale entries
It only considers clusterIP services
It only works on IPV4 single stack env
Assumes nodesubnet is the default /24 cidr

        Usage: ovn_cleanConntrack
        Help: ovn_cleanConntrack -h

After the execution logfile will be generated with the name ovn_cleanConntrack.DATE.log
```
Is the IP from ovn-k8s-mp0 interface contained in any k8s object that I can take with oc/kubectl? we are avoiding to ssh into the host.

2022-03-01 12:21 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +getConntrack
added the -h flag and function

2022-03-01 13:57 UTC, tssurya requested changes
hey @ptrnull ; I have reviwed it most are nits (I tried not to pick too much, sorry so feel free to ignore some of the nits as you deem fit)

The two most glaring things for me:
1) logic behind isContrackinClusterCIDR?
2) can we grep out the UDP ones beforehand?

2022-03-01 13:57 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +	if [[ "${src2}" == "${clusternetwork}"  ]]; then
umm what's this? I don't understand this logic. We'd never match on this right?
so you are trying to match the source of the reply tuple with clusterCIDR.2 ?? why?
example:
```
$ clusternetwork=$(oc get network cluster -o jsonpath='{ .spec.clusterNetwork[].cidr }' | cut -d'/' -f1 | sed -e 's/.$/2/')
$ echo $clusternetwork
10.128.0.2

AND

line="udp      17 28 src=192.168.96.39 dst=198.223.0.10 sport=41839 dport=53 [UNREPLIED] src=192.168.46.103 dst=192.168.96.39 sport=5353 dport=41839 mark=0 secctx=system_u:object_r:unlabeled_t:s0 zone=203 use=2"
$ src2=$(echo "${line}" | awk -F"src=" '{sub(/ .*/,"",$3);print $3}')
$ echo $src2
192.168.46.103
```
while in this case it will be mismatch because I took an example from the case, we still will never end up with an endpoint that is ".2", I am not sure I follow the logic here.

2022-03-01 13:57 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +    myep=$(echo -e "${endpoints}" | grep "${node}" | xargs | sed -e 's/ /\n/g')
you are filtering on nodes at this point in code... please add proper comments to doc string of isContrackInEndPoints function that details what you are trying to do.

2022-03-01 13:57 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +	#src2=$(echo "${line}" | awk -F"src=" '{sub(/ .*/,"",$2);print $2}')
nit: remove these?

2022-03-01 13:57 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +# D.D.D.D is the node-subnet from the node where the service
its not. its the ovn-k8s-mp0 interface IP.

2022-03-01 13:57 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +# src=A.A.A.A dst=B.B.B.B sport=42740 dport=5353 src=C.C.C.C
I'm not sure this is very helpful? example src=A.A.A.A & src=C.C.C.C ? what does that mean? :)

maybe replace these with one original tuple, show which was the clusterIP and which was the endpoint etc.

2022-03-01 13:57 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +	nodesubnet=$(oc get node "${node}" -o jsonpath='{.metadata.annotations.k8s\.ovn\.org/node-subnets}'  | jq .default | xargs | cut -d'/' -f1)
I guess technically it should be gwIP+1

2022-03-01 13:57 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +getConntrack
this is what get:
```
[surya@hidden-temple debug-scripts]$ ./ovn_cleanConntrack -h
This script does not actually clean up anything
It simply gives the potential list of things that might have to be cleaned up.
It only supports UDP stale entries
It only considers clusterIP services
It only works on IPV4 single stack env
Assumes nodesubnet is the default /24 cidr

	Usage: ovn_cleanConntrack
	Help: ovn_cleanConntrack -h

After the execution logfile will be generated with the name ovn_cleanConntrack.DATE.log

```
haha seems like you copied the sentences as such from slack, maybe we need to word them better? anyways I am not picky with this, upto you.
thanks for adding the helper!

2022-03-01 14:48 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +#IP for a node subnet with mask /24
done

2022-03-01 14:50 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +# getServices(): prepares a list of services
ack, modified, thanks!

2022-03-01 15:03 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +				while [ ${count} -le "${words}" ]; do
On the oc get... I have different cases, like f.ex:
```
TCP;172.30.58.192;443;
TCP TCP;172.30.110.67;9091 9092;
TCP TCP TCP;172.30.252.81;9091 9092 9093;
```
Looping over every line, then I'm checking if there are more than 1 word (if no, I'm in the first example, if yes, I'm in the second and third example, N) so I have to convert these 3 lines in:
```
TCP;172.30.58.192;443;
TCP;172.30.110.67;9091;
TCP;172.30.110.67;9092;
TCP;172.30.252.81;9091;
TCP;172.30.252.81;9092;
TCP;172.30.252.81;9093;
```
So I'm looping over the words and over the ports, maybe I could simplify it with only one loop, I'll check it.

2022-03-01 15:08 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +		for line in $(oc get endpoints -A -o jsonpath='{range .items[*].subsets[*]}{@.addresses[*].ip}{";"}{@.addresses[*].nodeName}{";"}{@.ports[*].port}{";"}{@.ports[*].protocol}{";"}{"\n"}{end}' ); do
This is a good catch, well done!

2022-03-01 15:09 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +function isContrackinSvcNetwork(){
changed

2022-03-01 15:09 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +function isContrackinEndPoints(){
changed

2022-03-02 10:16 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +	if [[ "${src2}" == "${clusternetwork}"  ]]; then
Was the implementation of "this was the original plan, we probably need a way to see if src of second tuple is clusterCIDR and eliminate all those which are not". I'll remove it.

2022-03-02 10:17 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +# D.D.D.D is the node-subnet from the node where the service
done

2022-03-02 10:18 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +	#src2=$(echo "${line}" | awk -F"src=" '{sub(/ .*/,"",$2);print $2}')
done

2022-03-02 10:23 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +		echo -e "\nFinal endpoints\n-----------\n${endpoints}" >> "${LOG}"
done

2022-03-02 10:44 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +	dst1O2=$(echo "${dst1}" | cut -d';' -f1 | cut -d'.' -f2)
Added to the helper.

2022-03-02 10:59 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +getConntrack
modified.

2022-03-02 10:59 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +		for conntrack in $(echo "${conntracks}" | sed 's/udp/\nudp/g' | sed 's/\[UNREPLIED\]//g' | sed 's/\[ASSURED\]//g' | tr -s ' '); do
yes, that is

2022-03-02 11:00 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +				while [ ${count} -le "${words}" ]; do
modified it.

2022-03-02 11:01 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +	if [[ "${src2}" == "${clusternetwork}"  ]]; then
no its not to be removed; like please explain the logic behind using 10.128.0.2? how is that checking if src of second tuple is in clusterCIDR?

2022-03-02 11:16 UTC, tssurya requested changes

2022-03-02 11:16 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +	if [[ "${src2}" == "${clusternetwork}"  ]]; then
we need to change this. the src will never equal the clusternetwork cidr right?

2022-03-02 11:16 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +				if ! isContrackinClusterCIDR "${conntrack}"; then
what we really want is to check if the src is in the cluster cidr right?? this is doing a negation; if the src is NOT in the clusterCIDR? please recheck your logic.

2022-03-03 09:43 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +    myep=$(echo -e "${endpoints}" | grep "${node}" | xargs | sed -e 's/ /\n/g')
done

2022-03-03 09:43 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +				if ! isContrackinClusterCIDR "${conntrack}"; then
fixed

2022-03-03 11:24 UTC, tssurya reviewed
@ptrnull : I haven't checked the line by line verification for your new changes like I did in the last iteration (I am hoping you ran it against the old conntrack list where the bug was observed). A few questions inline.

Thanks for the hard work.
I'll leave it to Dan for approval.

2022-03-03 11:24 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +			if isContrackInSvcNetwork "${conntrack}"; then
ok this lgtm.

2022-03-03 11:24 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +	echo "Checks for the Service CIDR to have one of the networks /8 /16 or /24"
please add the clusterCIDR limitation as well (assumption that its /8 from what I saw below?)

2022-03-03 11:24 UTC, tssurya commented on debug-scripts/ovn_cleanConntrack
> +	if [[ "${srcoc1}" == "${cnoc1}" && "${srcoc2}" == "${cnoc2}" && "${srcoc3}" == "${cnoc3}" ]]; then
so here we are assuming cidr is always /8 right? Is this the default value in user's env?

2022-03-03 11:50 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +	echo "Checks for the Service CIDR to have one of the networks /8 /16 or /24"
added, thanks.

2022-03-04 12:30 UTC, ptrnull commented on debug-scripts/ovn_cleanConntrack
> +clusternetwork=$(oc get network cluster -o jsonpath='{ .spec.clusterNetwork[].cidr }' | cut -d'/' -f1 | sed -e 's/.$/2/')
Informed in the helper function, we only cover the single stack IPv4 case.

2022-03-22 09:16 UTC, tssurya commented
@dcbw : I am merging this script in for now specially considering how we already presented it to the user over 2 weeks ago. If we have more bugs/concerns let's open a new PR and I hope @ptrnull when you get updates and improvement suggestions from the user you'll fix them in this rep/script as well.

2022-03-22 09:16 UTC, tssurya commented
/lgtm

2022-03-22 09:19 UTC, merged