Minor fixed found during demo preparation
openshift/network-tools pull request #68
Opened 2022-09-05 16:33 UTC by npinaeva

Use get_full_path for file inputs to make sure we convert relative path correctly.
Only use bash -c with braced commands for netnamespace
Add contacts in README

Signed-off-by: Nadia Pinaeva <npinaeva@redhat.com>

2022-09-06 19:23 UTC, flavio-fernandes requested changes
some ideas for improving full path. otherwise, lgtm.

2022-09-06 19:23 UTC, flavio-fernandes commented on debug-scripts/utils
> +  echo "$(cd "$(dirname "$local_path")"; pwd)/$(basename "$local_path")"
I second what @andreaskaris says here, @npinaeva . pushd seems a bit of overkill.
How about something like:
```
get_full_path() {
    FP="${NETWORK_TOOLS_INITIAL_DIR}/$1"
    readlink -e "$FP" || { >&2 echo "Bad path $FP"; exit 1; }
}
```

2022-09-07 11:12 UTC, npinaeva commented
You are absolutely right, I was too lazy to do that properly
Thanks for paying attention! PTAL if this update is better (notice that this function should also work with absolute path)

2022-09-07 15:36 UTC, flavio-fernandes reviewed
/lgtm

2022-09-07 15:36 UTC, flavio-fernandes commented on debug-scripts/utils
> +  if [[ "$1" = /* ]]; then
nice!

2022-09-07 15:43 UTC, merged